name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"
jobs:

  build:
    strategy:
      matrix:
        image:
          - centos7
          - centos8
          - debian9
          - debian10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        file: ${{ matrix.image }}.Dockerfile
        tags: devonm/molecule-test-${{ matrix.image }}:latest
