name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"
jobs:

  build:
    strategy:
      matrix:
        image:
          - centos7
          - centos8
          - debian9
          - debian10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: ${{ matrix.image }}.Dockerfile
        repository: devonm/molecule-test-${{ matrix.image }}
        tags: latest
